services:
  redis:
    image: "redis/redis-stack:latest"

  rabbitmq:
    image: "rabbitmq:4.0.3-management"

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.db-env
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - env/.project-env
      - env/.mq-env
      - env/.db-env
    depends_on:
      - postgres
      - rabbitmq
      - redis
    links:
      - postgres:postgres

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

  image_processing:
    build: ./image_processing
    env_file:
      - env/.mq-env
    depends_on:
      - web
      - rabbitmq

volumes:
  postgres_data: