services:
  redis:
    image: "redis/redis-stack:latest"

  rabbitmq:
    image: "rabbitmq:4.0.3-management"

  web:
    build: .
    expose:
      - 8000
    env_file:
      - env/.project-env
      - env/.mq-env
    depends_on:
      - rabbitmq
      - redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

  image_processing:
    build: ./image_processing
    env_file:
      - env/.mq-env
    depends_on:
      - web
      - rabbitmq
