IMAGE_STORE_PATH = 'images/'

RESOLUTION_SMALL = '100x100'
RESOLUTION_MEDIUM = '500x500'
RESOLUTION_LARGE = '900x900'
RESOLUTION_CHOICES = ((RESOLUTION_SMALL, 'Маленькое'), (RESOLUTION_MEDIUM, 'Среднее'), (RESOLUTION_LARGE, 'Большое'))
